# Generated by Django 2.1.5 on 2020-05-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
