# Generated by Django 2.1.5 on 2020-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('detail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
