# Generated by Django 2.1.5 on 2020-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('s_grade', models.ForeignKey(on_delete='on_delete', to='App.Grade')),
            ],
        ),
    ]
